import type { Topic } from './types.js';

// Built-in system-design topics for the Film / interview series.
//
// COMPLETE-SYSTEM LAW (docs/complete-system-law.md): every diagram beat is a full
// working system end-to-end. Beat 1 = naive complete. Interviewer follow-ups pressure
// a gap; the next beat is still complete with pieces added or reworked. Never progressive
// "assemble the final diagram" fragments (client+api with no store, limiter with no allow path).

export const TOPICS: Topic[] = [
  {
    slug: 'url-shortener',
    title: 'Designing a URL Shortener',
    tagline: 'How a long link becomes six characters',
    interviewPrompt: 'design a URL shortener',
    nodes: [
      { id: 'client', label: 'Client', x: 80, y: 330, shape: 'client' },
      { id: 'api', label: 'API', sub: 'shorten + resolve', x: 440, y: 330, shape: 'service' },
      { id: 'idgen', label: 'ID Gen', sub: 'base62', x: 440, y: 120, shape: 'component' },
      { id: 'kv', label: 'KV Store', sub: 'code → url', x: 820, y: 330, shape: 'db', tech: 'amazondynamodb' },
      { id: 'cache', label: 'Cache', sub: 'hot links', x: 820, y: 120, shape: 'cache', tech: 'redis' },
      { id: 'analytics', label: 'Click Queue', sub: 'async', x: 820, y: 540, shape: 'queue' },
    ],
    edges: [
      { from: 'client', to: 'api', label: 'GET /abc' },
      { from: 'idgen', to: 'api', dashed: true },
      { from: 'api', to: 'kv', label: 'write mapping' },
      { from: 'api', to: 'cache', label: 'read-through', dashed: true },
      { from: 'api', to: 'analytics', label: 'log click', dashed: true },
    ],
    beats: [
      {
        say: "Naive complete system: paste a long URL, hash it, store code→URL in a key-value store, redirect on lookup. Three boxes, it works.",
        show: 'Naive complete: Client → API → KV. Hash, store, redirect.',
        visible: ['client', 'api', 'kv'],
        highlight: ['client>api', 'api>kv'],
      },
      {
        say: "What breaks first: hash is long, truncating collides, and the write path is the ceiling once traffic ramps.",
        show: 'Pressure: collisions + write bottleneck on the same complete path.',
        visible: ['client', 'api', 'kv'],
        highlight: ['kv', 'api>kv'],
      },
      {
        say: "Rework code gen: counter ID, base62 encode. Still the same full path, now with a dedicated ID generator feeding the API.",
        show: 'Rework: Counter → base62 (ID Gen) still ends in KV lookup.',
        visible: ['client', 'api', 'idgen', 'kv'],
        highlight: ['idgen', 'idgen>api'],
      },
      {
        say: "Read path is the traffic: visit is lookup by code, 302 redirect. Same complete system, stress the resolve edge.",
        show: 'Same system, resolve path: code in → 302 out.',
        visible: ['client', 'api', 'idgen', 'kv'],
        highlight: ['client>api', 'api>kv'],
      },
      {
        say: "Hot links dominate. Add a read-through cache so the common path never hits the KV. Full system still shortens and redirects.",
        show: 'Add Redis read-through for hot links. Full path still works.',
        visible: ['client', 'api', 'idgen', 'kv', 'cache'],
        highlight: ['cache', 'api>cache'],
      },
      {
        say: "Clicks log off to a queue so the redirect stays instant. Complete production path: shorten, resolve, cache, async analytics.",
        show: 'Add async click queue. Redirect path stays complete and fast.',
        visible: ['client', 'api', 'idgen', 'kv', 'cache', 'analytics'],
        highlight: ['analytics', 'api>analytics'],
      },
    ],
  },
  {
    slug: 'rate-limiter',
    title: 'Designing a Rate Limiter',
    tagline: 'The bouncer that keeps your API standing',
    interviewPrompt: 'design a rate limiter',
    nodes: [
      { id: 'client', label: 'Client', x: 80, y: 330, shape: 'client' },
      { id: 'gw', label: 'Gateway', x: 440, y: 330, shape: 'service' },
      { id: 'limiter', label: 'Limiter', sub: 'per user', x: 440, y: 120, shape: 'component' },
      { id: 'redis', label: 'Redis', sub: 'counters', x: 820, y: 120, shape: 'cache', tech: 'redis' },
      { id: 'svc', label: 'Service', sub: 'allowed', x: 820, y: 330, shape: 'service' },
      { id: 'reject', label: '429', sub: 'over limit', x: 820, y: 540, shape: 'service' },
    ],
    edges: [
      { from: 'client', to: 'gw' },
      { from: 'gw', to: 'limiter' },
      { from: 'limiter', to: 'redis', label: 'atomic incr' },
      { from: 'gw', to: 'svc', label: 'token left' },
      { from: 'gw', to: 'reject', label: 'bucket empty' },
    ],
    beats: [
      {
        say: "Naive complete: every request hits the gateway, checks an in-memory per-user counter, then either reaches the service or gets a 429.",
        show: 'Naive complete: Client → Gateway → allow Service / deny 429.',
        visible: ['client', 'gw', 'limiter', 'svc', 'reject'],
        highlight: ['limiter', 'gw>svc', 'gw>reject'],
      },
      {
        say: "Fixed-window burst bug: 100 at 0:59 and 100 at 1:00, all legal. Same full path, the counter algorithm is the weak spot.",
        show: 'Same complete path. Fixed-window burst is the failure mode.',
        visible: ['client', 'gw', 'limiter', 'svc', 'reject'],
        highlight: ['limiter'],
      },
      {
        say: "Rework the algorithm to a token bucket, and put counters in Redis so every server behind the load balancer agrees. Full allow/deny path stays.",
        show: 'Rework: token bucket + Redis. Allow and deny still wired.',
        visible: ['client', 'gw', 'limiter', 'redis', 'svc', 'reject'],
        highlight: ['redis', 'limiter>redis'],
      },
      {
        say: "Per request: token left, pass through. Bucket empty, 429 plus Retry-After. Walk the full path both ways.",
        show: 'Full path: token left → Service. Empty → 429 + Retry-After.',
        visible: ['client', 'gw', 'limiter', 'redis', 'svc', 'reject'],
        highlight: ['svc', 'reject', 'gw>svc', 'gw>reject'],
      },
      {
        say: "Tradeoff: fixed-window is cheap, sliding-log is exact, token bucket is the middle. Atomic check via Redis Lua so two servers cannot both win.",
        show: 'Same system. Senior detail: atomic Lua check in Redis.',
        visible: ['client', 'gw', 'limiter', 'redis', 'svc', 'reject'],
        highlight: ['redis', 'limiter>redis'],
      },
      {
        say: "If Redis blinks: fail open or fail closed? Pick on purpose. The complete system still has both exits.",
        show: 'Failure mode on the full path: fail open vs fail closed.',
        visible: ['client', 'gw', 'limiter', 'redis', 'svc', 'reject'],
        highlight: ['redis'],
      },
    ],
  },
  {
    slug: 'news-feed',
    title: 'Designing a News Feed',
    tagline: 'Why your feed loads before you finish scrolling',
    interviewPrompt: 'design a news feed',
    nodes: [
      { id: 'author', label: 'Author', sub: 'posts', x: 80, y: 120, shape: 'client' },
      { id: 'writeapi', label: 'Write API', x: 440, y: 120, shape: 'service' },
      { id: 'fanout', label: 'Fan-out Worker', x: 440, y: 330, shape: 'compute' },
      { id: 'feedcache', label: 'Feed Cache', sub: 'per follower', x: 820, y: 330, shape: 'cache', tech: 'redis' },
      { id: 'reader', label: 'Follower', x: 80, y: 540, shape: 'client' },
      { id: 'readapi', label: 'Read API', x: 440, y: 540, shape: 'service' },
      { id: 'celeb', label: 'Celebrity', sub: 'skip fan-out', x: 80, y: 330, shape: 'client' },
      { id: 'merge', label: 'Merge', sub: 'at read time', x: 820, y: 540, shape: 'compute' },
    ],
    edges: [
      { from: 'author', to: 'writeapi' },
      { from: 'writeapi', to: 'fanout' },
      { from: 'fanout', to: 'feedcache', label: 'push to followers' },
      { from: 'reader', to: 'readapi' },
      { from: 'readapi', to: 'feedcache', label: 'read feed' },
      { from: 'celeb', to: 'writeapi', label: 'post', dashed: true },
      { from: 'readapi', to: 'merge', label: 'pull celebs' },
      { from: 'merge', to: 'feedcache', label: 'merge', dashed: true },
    ],
    beats: [
      {
        say: "Complete fan-out-on-write system: author posts, worker copies into each follower's feed cache, reader loads with one cache read.",
        show: 'Complete fan-out-on-write: post → fan-out → cache; read is one lookup.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi'],
        highlight: ['fanout', 'fanout>feedcache', 'readapi>feedcache'],
      },
      {
        say: "Celebrity posts explode the write path. Same full system, the fan-out worker is the blow-up point.",
        show: 'Same complete system. Celebrity = millions of fan-out writes.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi'],
        highlight: ['fanout'],
      },
      {
        say: "Hybrid rework: normal users still fan out on write. Celebrity posts skip fan-out and merge in at read time. Full write and read paths remain.",
        show: 'Rework hybrid: fan-out normals, merge celebs at read. Still complete.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi', 'celeb', 'merge'],
        highlight: ['celeb', 'merge', 'readapi>merge'],
      },
      {
        say: "Gate fan-out on active followers so dormant accounts do not burn write capacity. Same hybrid system.",
        show: 'Tune: only fan out to active followers. Hybrid path stays.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi', 'celeb', 'merge'],
        highlight: ['fanout', 'fanout>feedcache'],
      },
      {
        say: "Rank after merge: recency, affinity, engagement. Still one complete feed path.",
        show: 'Same system + ranking on the merged home timeline.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi', 'celeb', 'merge'],
        highlight: ['readapi', 'merge'],
      },
      {
        say: "Summary on the full graph: precompute the common path, compute the expensive path on demand.",
        show: 'Full system takeaway: precompute common, lazy expensive.',
        visible: ['author', 'writeapi', 'fanout', 'feedcache', 'reader', 'readapi', 'celeb', 'merge'],
        highlight: ['feedcache', 'merge'],
      },
    ],
  },
  {
    slug: 'chat-system',
    title: 'Designing a Chat System',
    tagline: 'Stay connected, and never lose a message',
    interviewPrompt: 'design a chat system like WhatsApp',
    nodes: [
      { id: 'a', label: 'Client A', x: 80, y: 120, shape: 'client' },
      { id: 'gw', label: 'WS Gateway', x: 440, y: 120, shape: 'service' },
      { id: 'msg', label: 'Message Svc', x: 440, y: 330, shape: 'service' },
      { id: 'store', label: 'History Store', x: 820, y: 330, shape: 'db', tech: 'postgresql' },
      { id: 'queue', label: 'Fan-out Log', x: 820, y: 120, shape: 'queue', tech: 'apachekafka' },
      { id: 'b', label: 'Client B', x: 80, y: 540, shape: 'client' },
      { id: 'presence', label: 'Presence Map', sub: 'user → server', x: 440, y: 540, shape: 'cache', tech: 'redis' },
    ],
    edges: [
      { from: 'a', to: 'gw', label: 'websocket' },
      { from: 'gw', to: 'msg' },
      { from: 'msg', to: 'store', label: 'persist first' },
      { from: 'msg', to: 'queue', label: 'publish' },
      { from: 'queue', to: 'b', label: 'deliver', dashed: true },
      { from: 'gw', to: 'b', label: 'online push', dashed: true },
      { from: 'msg', to: 'presence', label: 'which server?' },
    ],
    beats: [
      {
        say: "Naive complete online chat: A holds a WebSocket to a gateway, message routes straight to B's open socket. Works when both are online on one server.",
        show: 'Naive complete online path: A → Gateway → B.',
        visible: ['a', 'gw', 'b'],
        highlight: ['a>gw', 'gw>b'],
      },
      {
        say: "Durability: message service assigns id + server timestamp and writes history before anything else. Full path now includes the store.",
        show: 'Add persist-first: A → svc → store, then delivery.',
        visible: ['a', 'gw', 'msg', 'store', 'b'],
        highlight: ['store', 'msg>store'],
      },
      {
        say: "Publish to a fan-out log so every online participant gets a push. Offline recipients still have the store.",
        show: 'Complete: persist, publish on Kafka, deliver online.',
        visible: ['a', 'gw', 'msg', 'store', 'queue', 'b'],
        highlight: ['queue', 'msg>queue', 'queue>b'],
      },
      {
        say: "Multi-server: presence map in Redis says which box holds B's socket. Full send path looks up, then forwards or queues.",
        show: 'Add presence map. Still end-to-end for online and offline.',
        visible: ['a', 'gw', 'msg', 'store', 'queue', 'b', 'presence'],
        highlight: ['presence', 'msg>presence'],
      },
      {
        say: "Recipient offline? Already stored. Deliver on reconnect and fire a push. Same complete system, stress the offline branch.",
        show: 'Offline branch on the full system: store + reconnect delivery.',
        visible: ['a', 'gw', 'msg', 'store', 'queue', 'b', 'presence'],
        highlight: ['store', 'b'],
      },
      {
        say: "Order by server timestamp. The store is source of truth. Walk the full path once more for ordering.",
        show: 'Full system: order by server time from the history store.',
        visible: ['a', 'gw', 'msg', 'store', 'queue', 'b', 'presence'],
        highlight: ['store'],
      },
    ],
  },
  {
    slug: 'cdn-caching',
    title: 'How a CDN Actually Works',
    tagline: 'Why a US site loads instantly in Tokyo',
    interviewPrompt: 'explain how a CDN actually works',
    nodes: [
      { id: 'user', label: 'User', sub: 'Tokyo', x: 80, y: 330, shape: 'client' },
      { id: 'edge', label: 'Edge PoP', sub: 'cache', x: 440, y: 330, shape: 'cache', tech: 'cloudflare' },
      { id: 'origin', label: 'Origin', sub: 'Virginia', x: 820, y: 330, shape: 'service', tech: 'nginx' },
      { id: 'store', label: 'Object Store', x: 820, y: 120, shape: 'db', tech: 'amazons3' },
      { id: 'purge', label: 'Purge API', x: 440, y: 120, shape: 'service' },
    ],
    edges: [
      { from: 'user', to: 'edge', label: 'nearest PoP' },
      { from: 'user', to: 'origin', label: 'no CDN', dashed: true },
      { from: 'edge', to: 'origin', label: 'on miss' },
      { from: 'origin', to: 'store' },
      { from: 'purge', to: 'edge', label: 'invalidate', dashed: true },
    ],
    beats: [
      {
        say: "Naive complete: Tokyo user hits Virginia origin, origin reads the object store. Works, just slow.",
        show: 'Naive complete: User → Origin → Object Store. Correct, far.',
        visible: ['user', 'origin', 'store'],
        highlight: ['user>origin', 'origin>store'],
      },
      {
        say: "Insert an edge PoP near the user. On a cache hit the full path is User → Edge only for the response, with origin still there for misses.",
        show: 'Add edge. Hit path is near the user; origin still in the system.',
        visible: ['user', 'edge', 'origin', 'store'],
        highlight: ['edge', 'user>edge'],
      },
      {
        say: "Miss path: edge fetches origin once, serves the user, keeps a copy. Full miss path is still end-to-end.",
        show: 'Complete miss: User → Edge → Origin → Store, then cache.',
        visible: ['user', 'edge', 'origin', 'store'],
        highlight: ['edge>origin', 'origin'],
      },
      {
        say: "TTL on every object bounds how long the edge may serve a copy. Same complete CDN system.",
        show: 'Same system + TTL policy on the edge cache.',
        visible: ['user', 'edge', 'origin', 'store'],
        highlight: ['edge'],
      },
      {
        say: "Purge API invalidates a key across PoPs when you cannot wait for TTL. Full system now includes control plane.",
        show: 'Add Purge API. Hit/miss path stays; invalidation is explicit.',
        visible: ['user', 'edge', 'origin', 'store', 'purge'],
        highlight: ['purge', 'purge>edge'],
      },
      {
        say: "Cache key is everything. Wrong cookies or query params and you leak the wrong page. Same full system, stress the key.",
        show: 'Full CDN system. Cache key is the safety rail.',
        visible: ['user', 'edge', 'origin', 'store', 'purge'],
        highlight: ['edge'],
      },
    ],
  },
];
